function dFC = dFCstream2dFC(dFCstream)

% FUNCTION dFC = dFCstream2dFC(dFCstream)
% takes dFCstream as input ('2D' or '3D') and calculates dFC [FxF] matrix,
% where F is the number of network frames in the input dFCstream.
%   
% input: dFCstream --> generated by TS2dFCstream (2D or 3D)
%
% Example: dfc = dFCstream2dFC(dfcstream)
%
% Reference: Lucas Arbabyazd et al. (2020) MethodsX

if (ndims(dFCstream) == 3)
    FCstr = Matrix2Vec(dFCstream);
end

if (ndims(dFCstream) == 2)
    FCstr = dFCstream;
end

if size(dFCstream,2) > 20000
    disp('Caution! If length of your dFCstream > 20,000 time-points, this')
    disp('function may take one minutes, if you persist, please comment me!')
    return
end
 
dFC = corr(FCstr);