function MC3=dFCstream2Trimers(dFCstream)

% FUNCTION MC3=dFCstream2Trimers(dFCstream)
% takes dFCstream as input ('2D' or '3D') and calculates "trimers" of meta-connectivity 
% (MC) [nxnxn] matrix, where n is the number of nodes in your network.
% You may use this function instead of dFCstream2MC if number of 
% nodes in your network > 200 regions.
%
% input: dFCstream --> generated by FCstr2dFCstream (2D or 3D)
%
% Example: MC3=dFCstream2Trimers(dfcstream)
%
% Reference: Lucas Arbabyazd et al. (2020) MethodsX

if (ndims(dFCstream) == 2)
    FCstr = Vec2Matrix(dFCstream);
end

if (ndims(dFCstream) == 3)
    FCstr = dFCstream;
end

n = size(FCstr,1);
MC3 = zeros(n,n,n);
for i = 1:n
    var1(:,:)=FCstr(:,i,:);
    var2=corr(var1');
    var2(isnan(var2))=0;
    var2(var2==1)=0;
    MC3(:,:,i)=var2;
end


